### ISSUE TITLE
在3090显卡 CUDA11.0 环境下编译的问题

### ISSUE THREAD

**Issue by Watebear** [YonghaoHe/LFD-A-Light-and-Fast-Detector#12]
您好，我的显卡是3090，用的是CUDA11.0，在执行 python3 setup.py build_ext 的时候遇到问题：

/home/dddzz/worksapce/Codes/FaceDetection2/LFD-A-Light-and-Fast-Detector-master/venv/lib/python3.8/site-packages/torch/cuda/__init__.py:104: UserWarning: 

GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.

The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75.

If you want to use the GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))

:/usr/local/cuda-11.0/bin/nvcc -DWITH_CUDA -I/home/dddzz/worksapce/Codes/FaceDetection2/LFD-A-Light-and-Fast-Detector-master/venv/lib/python3.8/site-packages/torch/include -I/home/dddzz/worksapce/Codes/FaceDetection2/LFD-A-Light-and-Fast-Detector-master/venv/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/home/dddzz/worksapce/Codes/FaceDetection2/LFD-A-Light-and-Fast-Detector-master/venv/lib/python3.8/site-packages/torch/include/TH -I/home/dddzz/worksapce/Codes/FaceDetection2/LFD-A-Light-and-Fast-Detector-master/venv/lib/python3.8/site-packages/torch/include/THC -I:/usr/local/cuda-11.0/include -I/home/dddzz/worksapce/Codes/FaceDetection2/LFD-A-Light-and-Fast-Detector-master/venv/include -I/usr/include/python3.8 -c lfd/model/utils/build/nms/src/cuda/nms_kernel.cu -o build/temp.linux-x86_64-3.8/lfd/model/utils/build/nms/src/cuda/nms_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=nms_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14

unable to execute ':/usr/local/cuda-11.0/bin/nvcc': No such file or directory

error: command ':/usr/local/cuda-11.0/bin/nvcc' failed with exit status 1

请问应该从文件中哪些地方进行修改，来匹配我的硬件设备。非常感谢！

**Comment by YonghaoHe** [comment]
@Watebear 很明显，提示你Pytorch的版本和当前的cuda版本不兼容，你先保证pytorch能够正常安装使用。

**Comment by Watebear** [comment]
> @Watebear 很明显，提示你Pytorch的版本和当前的cuda版本不兼容，你先保证pytorch能够正常安装使用。
这个问题我解决了，不是兼容问题，而是3090的算力太高（8.6），需要手动降低算力。
在编译前输入： export TORCH_CUDA_ARCH_LIST="7.5"
这样就可以解决了。
非常感谢您的开源！

**Comment by Watebear** [comment]
> @Watebear 很明显，提示你Pytorch的版本和当前的cuda版本不兼容，你先保证pytorch能够正常安装使用。

在后面跑训练脚本的时候，同样由于30显卡的问题，导致了报错：
<class 'RuntimeError'>
RuntimeError('cuda runtime error (209) : no kernel image is available for execution on the device at lfd/model/losses/build/sigmoid_focal_loss/src/cuda/sigmoid_focal_loss_cuda.cu:128')
  File "WIDERFACE_train/WIDERFACE_LFD_XS.py", line 261, in <module>
    training_executor.run()


我在用现有的环境跑自己的写的脚本的时候，都是正常的。请问本项目显卡相关的设置，在那里能改，我想通过改项目代码的方式来解决这个问题，请问您能否给些提示？
